spring.application.name=weather

spring.db.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:weather_db}
spring.db.username=${DB_USER:postgres}
spring.db.password=${DB_PASSWORD:admin}

openweather.api.key=${OPENWEATHER_API_KEY:}

session.timeout.hours=24
session.cookie.id=SESSION_ID
session.sliding.window.minutes=30